### ISSUE TITLE
Remove Transparency from Images

### ISSUE THREAD

**Issue by leoherzog** [akirk/friends-send-to-e-reader#2]
Great plugin, thanks @akirk!

Some posts might have images with alpha transparency, such as [xkcd.com](https://xkcd.com). These show up as black boxes on Kindle. Would it be possible to add a "convert transparency in images to white" setting to this plugin? When I had [a Bash script](https://gist.github.com/leoherzog/1dcffe776af200cd9117) doing something similar to this plugin, I used Imagemagick like so:

`mogrify -colorspace sRGB -background white -format jpg -alpha remove ./*.png`

**Comment by akirk** [comment]
Thank you! The problem with the missing image actually was a misaligned file index inside the Mobi. I have fixed that but additionally removed the alpha channel, I hope both fixes together make it work for you!
